name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install boost
      uses: MarkusJx/install-boost@v2.0.0
      id: install-boost
      with:
        boost_version: 1.76.0
        # boost_install_dir: /home/runner/work/cpp_PdfMerge/cpp_PdfMerge/
    - uses: actions/checkout@v2
    - name: make
      run: make
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
    - name: make check
      run: make check
